### ISSUE TITLE
项目启动时报错：ValueError

### ISSUE THREAD

**Issue by Yuerchu** [essesoul/Cloudreve-AfdianPay#10]
项目环境是宝塔8.0.5，python环境3.11.4

运行时终端打印内容：
Cloudreve Afdian Pay Server 已启动
Github: https://github.com/essesoul/Cloudreve-AfdianPay
-------------------------
程序运行端口：None
Traceback (most recent call last):
File "/www/wwwroot/Cloudreve_Pay/cloudreve_pay.py", line 112, in <module>
server = pywsgi.WSGIServer(('0.0.0.0', int(port)), app)
^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'

.env内容如下：
SITE_URL="https://example.com"
USER_ID="myUserID"
TOKEN="MyToken"
PORT="5000"

**Comment by essesoul** [comment]
没读到配置文件，看一下依赖有没有安装
使用`pip install -r requirements.txt`即可安装依赖
