### ISSUE TITLE
支付时日志显示404

### ISSUE THREAD

**Issue by zxcv-12345** [essesoul/Cloudreve-AfdianPay#5]
logs如下

"PRI * HTTP/2.0" 400 - 0.000155
"POST /order/create HTTP/1.1" 200 247 0.004961
"POST /order/create HTTP/1.1" 200 247 0.005561
"POST /afdian HTTP/1.1" 200 126 1.651144
"POST /order/create HTTP/1.1" 200 247 0.006289
 "POST /order/create HTTP/1.1" 200 247 0.005359
"POST /order/create HTTP/1.1" 200 247 0.005304
 "/*àCookie: mstshash=Administr" 400 - 0.000145

**Comment by zxcv-12345** [comment]
并且支付之后订单等都正常创建了，后台显示“未支付”实际上却是已经支付了导致无法自动到账下发。

**Comment by zxcv-12345** [comment]
> 请先检查一下`.env`文件中的内容、[爱发电开发者](https://afdian.net/dashboard/dev)页面的`Webhook URL`是否都填写正确
> 
> 如果还是存在问题，则需要检查一下程序目录下的数据库文件`afdian_pay.db` 可以使用[sqlitestudio](https://github.com/pawelsalawa/sqlitestudio)等工具打开该文件 请检查`afdian_pay`表中`order_no`列数据是否有正常写入
> 
> 如需更多协助，请将程序目录下的数据库文件`afdian_pay.db`发送至邮箱：[Gary@dtnetwork.top](mailto:Gary@dtnetwork.top)
> 
> 另外，由于目前程序还不完善，暂时还无法显示或者保存日志 后续更新中会考虑加上**保存日志**的功能

ok我晚点去看看db，我是后台守护运行的py，日志是直接输出到了指定的logs文件里面

**Comment by zxcv-12345** [comment]
我看了一下他存储的db里面oreder_non那一列他是正常写入了的

**Comment by essesoul** [comment]
应该是回调的问题，检查一下[爱发电开发者](https://afdian.net/dashboard/dev)页面的Webhook URL是否填写正确

**Comment by zxcv-12345** [comment]
> 应该是回调的问题，检查一下[爱发电开发者](https://afdian.net/dashboard/dev)页面的Webhook URL是否填写正确

没填错啊。

**Comment by essesoul** [comment]
还需要帮助吗，需要的话再reopen
